### ISSUE TITLE
Overall feedback

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/university-of-remainia#14]
I suspect that there is some overall thoughts about how the site is going up and together. 

I think that:
#### Main Page
- [x] The banner should be moved up -- the heading is big, and too much padding. Shrink it.
- [x] Make text darker.
- [x] Remove contact form in the footer entirely?
- [ ] Add example profiles of featured faculty. 
- [ ] Add Twitter and Facebook. 
- [x] The navigation doesn't look very "University". I think that's OK, but I wish I could find a crappier theme. Amazing how hard this actually is. I could just start over with bootstrap? 
#### Research Page, "No but Seriously"
- [x] This needs a lot more content, but I'm not sure what should go here. Ideas? 
- [x] Far too wide. Cap content at 800px, centered. 
#### Faculty
- [x] Should we organize by school? Seems a bit odd. Will probably look fine if we implement an accordion. On click, see all faculty members in each school? For now, I think we should just put names in, and slowly filly it out manually - no need to make a solution for a problem (too many names) that doesn't exist yet. 
#### Apply
- [x] Looks OK... but should really not be in a google form. Should be native to the site, maybe, and automatically fill out details in markdown. I can look into this, but will take a lot more development time. 
#### Faculty Example - /faculty/neylon
- [ ] Looks OK; Going to be hard to fill out funding and research. Maybe we can get these manually?

**Comment by cameronneylon** [comment]
Ok, so working through these:
- Agree on the lay out and darker text. 
- Agree on removing the contact form, probably not idea to encourage too much in the way of contact on these kind of thing
- Agree that the navigation isn't that important, also this relates to the organisation by school. I think its worth having some sort of subject classification, it depends a little on how many people we wend up with of course

Research pages/"no, but seriously"
- Yes to width constraint
- Action me to write text, I'm not actually sure we need the "no, but seriously" page any more as that was really to provide context for the "joke" of the name which we're no longer pursuing. But it could contain some FAQs which I can write up

Faculty
- Agree that probably the simplest is the best, particularly as we start. The object is to take a person to the stories that will most interest them, but its a little hard to know how to do that at this stage.

Apply
- I think its fine and seems to work. Automating it would be great but its a lot of work, again to solve a problem we might not have?

Example
- I'll use this to do a quick and dirty script to pull from ORCID as an example and work from there.

**Comment by RichardLitt** [comment]
Ok, did some work today. See checks above. I think we're almost good to go - let me know if you want anything tweaked! At this point, I think I am waiting on you for the following. 
- [ ] Add an example profile of a faculty. you?
- [ ] Get a twitter account.
- [x] Get text from @cameronneylon for the "No but seriously" page

Is there anything you want me to do, now?

**Comment by cameronneylon** [comment]
Thanks, yes, you're waiting on me. I've put together some scripts for populating the profiles but that involved some yak shaving. I'll aim to put more text and other things together today and then test that by populating my own profile.

Target of finishing this by Wednesday.

**Comment by RichardLitt** [comment]
We all love yaks. :)

**Comment by cameronneylon** [comment]
Yaks are great, although I'm not sure its a good sign when its me updating
the API wrapper for a major piece of shared infrastructure :-/

**Comment by RichardLitt** [comment]
That is not ideal. Do you need help with anything?

**Comment by cameronneylon** [comment]
Nah, its fine. I've got everything fixed that I wanted to, just need to
push out the templated profiles now. Actually one thing would be useful.
I'm currently generating publication and funding and was intending just
inject that as markdown into the profile.md file. Is that the appropriate
way to do it?

**Comment by RichardLitt** [comment]
Yep!

**Comment by RichardLitt** [comment]
@cameronneylon I think we've got all this done. The only thing I need to do is finish #6 (Create a Twitter account) and make sure that the front page is populated from faculty, not from my lorem ipsum.

**Comment by RichardLitt** [comment]
Tracking this in #16 and #6.
