### ISSUE TITLE
Populate "featured faculty" from the faculty pages at random

### ISSUE THREAD

**Issue by cameronneylon** [RichardLitt/university-of-remainia#16]
The featured faculty sidebar would ideally pull a random profile from the faculty director and display the first few lines of the content, perhaps with a thumbnail of the image. Not sure how to go about doing this but presumably feasible?

**Comment by RichardLitt** [comment]
Yeah. I was waiting for some more profiles. I can do this!

**Comment by RichardLitt** [comment]
Closing this.
