### ISSUE TITLE
Set up a Twitter account

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/university-of-remainia#6]

**Comment by RichardLitt** [comment]
@cameronneylon Is this needed before we can launch? 

I can set it up, just making sure.

**Comment by RichardLitt** [comment]
I think it is, looking at #14. So:

`@britishresearchineu`. Sound good to you?

**Comment by cameronneylon** [comment]
Yep, that works for me.

**Comment by RichardLitt** [comment]
Waiting on #8.

**Comment by RichardLitt** [comment]
Done. @ukresearchineu ended up being short enough. Password emailed to you
