### ISSUE TITLE
Set up an email account

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/university-of-remainia#8]

**Comment by RichardLitt** [comment]
@cameronneylon Is this needed before we can launch? 

I can set it up.

**Comment by RichardLitt** [comment]
Looking into ways to do this:

- Use another gmail account. This should work.
  - [x] Check that you don't violate their terms of service by having multiple accounts. _It doesn't._
  - Using a custom domain would cost around $50 a year. 
  - I think this is the easiest option, as we're probably both used to it. 
- Use [Proton Mail](https://protonmail.com/). I would like to do this, but it looks like it is $48 a year for custom domains. https://protonmail.com/support/knowledge-base/paid-plans.
- [Mailpile](https://www.mailpile.is/faq/). This is a custom email server; not what we want.
- Use Webfaction. I have an account here, and can use their native Squirrel mail to make free  `@british-research-in.eu` accounts. We can forward these to gmail, and respond from there. Technically more likely to have bugs, but should work fine. All you'd need to do would be to point the MX records of the site at my webfaction server. 

@cameronneylon, I've got a couple of questions:
- Who is the registrar for your domain? Do they provide email hosting? 
- Are you ok with using Gmail?
- Do you want to have the account `@british-research-in.eu`?
- If not, what would you suggest for the email name?

**Comment by cameronneylon** [comment]
I'm using Dreamhost for the registration and there is a facility to create simple forward-only email addresses or "real" ones. Seems to be free so that's easy enough. Shall I just set up a forward that goes to both of us with admin@british-research-in.eu as the address?

**Comment by RichardLitt** [comment]
That sounds good to me! Go ahead and do it.

**Comment by cameronneylon** [comment]
Done

**Comment by RichardLitt** [comment]
I sent a test email and didn't get it; can you verify this works? (Sorry!)

**Comment by cameronneylon** [comment]
Odd, I got the test message...I had it going to the burntfen address. Just changed it for the gmail and sent another test message. See if that works.

**Comment by RichardLitt** [comment]
Done. Let's add this to the front page.

**Comment by RichardLitt** [comment]
Close pending #22.

**Comment by RichardLitt** [comment]
Works.
